### ISSUE TITLE
ubuntu12.04 error

### ISSUE THREAD

**Issue by liuhill** [hughsk/image-resize-stream#1]
950 error canvas@1.1.3 install: `node-gyp rebuild`
950 error Exit status 1
951 error Failed at the canvas@1.1.3 install script.
951 error This is most likely a problem with the canvas package,
951 error not with npm itself.
951 error Tell the author that this fails on your system:
951 error     node-gyp rebuild
951 error You can get their info via:
951 error     npm owner ls canvas
951 error There is likely additional logging output above.
952 error System Linux 3.2.0-29-generic
953 error command "/home/wwwroot/nodejs/bin/node" "/home/wwwroot/nodejs/bin/npm" "install" "image-resize-stream" "-gd"
954 error cwd /home/wwwroot/kper
955 error node -v v0.10.24
956 error npm -v 1.3.21
957 error code ELIFECYCLE
958 verbose exit [ 1, true ]

OS:unbuntu12.04
node：v0.10.24
npm:1.3.21

**Comment by hughsk** [comment]
"This is most likely a problem with the canvas package"

You should open an issue in [node-canvas](https://github.com/learnboost/node-canvas) instead :)
